# Generated by Django 4.2.6 on 2023-10-15 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=10)),
                ('creditos', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('imagem', models.CharField(max_length=150)),
            ],
        ),
    ]
