# Generated by Django 4.2.6 on 2023-10-17 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'nebulosa'), ('GALAXIA', 'galáxia')], default='', max_length=150),
        ),
    ]
