# Generated by Django 4.2.6 on 2023-10-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALAXIA', 'galáxia'), ('NEBULOSA', 'nebulosa')], default='', max_length=150),
        ),
    ]
