# Generated by Django 4.2.6 on 2023-10-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_fotografia_usuario_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALAXIA', 'galáxia'), ('NEBULOSA', 'nebulosa')], default='', max_length=150),
        ),
    ]
